name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        working-directory: ./pi
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run mypy type tests
        working-directory: ./pi
        run: mypy --strict $(git ls-files '*.py')


      - name: Run tests with pytest
        working-directory: ./pi
        run: pytest 