name: pi tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./pi/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: ./pi
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run mypy type tests
        working-directory: ./pi
        run: mypy --strict --implicit-reexport --ignore-missing-imports $(git ls-files '*.py')

      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests with pytest-mocha
        working-directory: ./pi/src
        run: pytest --mocha test/ --ignore=test/test_hardware --ignore=test/test_sim --ignore=test/test_network --ignore=test/test_on_pi